#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          thehive
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: TheHive: a FOSS Information Security Incident Management Platform
### END INIT INFO

NAME=thehive
DAEMONDIR=/opt/thehive
DAEMON=$DAEMONDIR/bin/thehive
PIDDIR=/var/run/thehive
PIDFILE=$PIDDIR/pid
DAEMONUSER=thehive
CONFIGFILE=/etc/thehive/application.conf
LISTENPORT=9090
DAEMON_OPTS=
PATH=/sbin:/bin:/usr/sbin:/usr/bin

test -x $DAEMON || exit 0

if test -f /etc/default/$NAME
then
    . /etc/default/$NAME
fi

. /lib/lsb/init-functions

check_for_upstart() {
  if init_is_upstart; then
    exit $1
  fi
}

check_config_file() {
  if test ! -e $CONFIGFILE
  then
    mkdir -p $(dirname $CONFIGFILE) 2>/dev/null || true
    cat >> $CONFIGFILE <<- _EOF_
      # Secret key
      # ~~~~~
      # The secret key is used to secure cryptographics functions.
      # If you deploy your application to several instances be sure to use the same key!
     play.crypto.secret="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)"
_EOF_
    chown $DAEMONUSER $CONFIGFILE
    chmod o-rwx $CONFIGFILE
  fi
}

case "$1" in
  start)
    check_for_upstart 1
    check_config_file
    log_daemon_msg "Starting TheHive" $NAME || true
    if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --chdir $DAEMONDIR --exec $DAEMON -- -Dconfig.file=$CONFIGFILE -Dhttp.port=$LISTENPORT -Dpidfile.path=$PIDFILE $DAEMON_OPTS
    then
      log_end_msg 0 || true
    else
      log_end_msg 1 || true
    fi
    ;;

  stop)
    check_for_upstart 1
    log_daemon_msg "Stopping TheHive" $NAME || true
    if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    then
      log_end_msg 0 || true
    else
      log_end_msg 1 || true
    fi
    ;;

  status)
    check_for_upstart 1
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;


  restart)
    stop
    start
    ;;

  *)
    log_action_msg "Usage: /etc/init.d/thehive {start|stop|restart|status}" || true
    exit 1
esac
